id = "shale-theme"
name = "Shale Theme"
version = "0.1.0"
schema_version = 1
authors = ["Smit Patil <smit@smit.codes>"]
description = "Shale theme for Zed"
repository = "https://github.com/smit4k/zed-shale"
